### ISSUE TITLE
Some files in the benchmark are lost

### ISSUE THREAD

**Issue by coffezhou** [haoyang9804/RecBi#1]
In the directory of llvmbugs, bug 26734 is missed. Also, the "fail.c" of bug 24516 is lost.

**Comment by haoyang9804** [comment]
Thanks for pointing it out. I will try to add the lost ones to this benchmark later

**Comment by haoyang9804** [comment]
> In the directory of llvmbugs, bug 26734 is missed. Also, the "fail.c" of bug 24516 is lost.

Thanks for pointing it out. I will try to add the lost ones to this benchmark later

**Comment by haoyang9804** [comment]
The missing file has been added to the benchmark

**Comment by coffezhou** [comment]
Thank you for adding the lost files in the benchmark!
