### ISSUE TITLE
Could you please share the code for run the benchmark for gcc compiler?

### ISSUE THREAD

**Issue by coffezhou** [haoyang9804/RecBi#2]
Hi, 
Could you please share the code for run the benchmark for gcc compiler? The code for llvm cannot be used to run the benchmark of gcc. I try to modify the code of llvm for gcc, but it does not work. 
Thanks!

**Comment by haoyang9804** [comment]
Sorry for the inconvenience. As is shown in README, our experimental data about gcc was obtained through svn but currently gcc svn repository has been abandoned and has been moved to git.  It's requires much manual effort to find the corresponding gcc bugs in git repository. Therefore, we forgoes this part currently.

**Comment by coffezhou** [comment]
Thanks for reply! 
I have the old repository based on svn for gcc , so your code should work for me.  If possible，please share your code for me. My email is cszide@163.com.
Besides，llvm svn repository is also abandoned and has been moved to git. 
Thanks!
